- hosts: google-*
  become: yes
  tasks:
   - name: Get apache zookeeper
     unarchive: 
       src: https://dlcdn.apache.org/drill/drill-1.19.0/apache-drill-1.19.0.tar.gz
       dest: /home/suhailmsu21
       remote_src: True 
       owner: suhailmsu21             
   - name: Deleting existing drill-override file
     raw: rm -r -f /home/suhailmsu21/apache-drill-1.19.0/conf/drill-override.conf
   - name: Creating drill-override file
     raw: touch /home/suhailmsu21/apache-drill-1.19.0/conf/drill-override.conf     
   - name: Editing drill-override.conf     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/apache-drill-1.19.0/conf/drill-override.conf
       insertafter: EOF
       block: |     
          drill.exec:{
            cluster-id: "cluster1",
            zk.connect: "google-1:2181,google-2:2181,google-3:2181,google-4:2181"
          }
       backup: yes
       owner: suhailmsu21 

   - name: Get apache hadoop
     get_url: 
       url: https://github.com/suhailshaik98/Configure-Apache-Hadoop/raw/main/drill-on-yarn.conf
       dest: /home/suhailmsu21/apache-drill-1.19.0/conf
       backup: yes
       owner: suhailmsu21
   - name: Editing drill-env.sh File
     ansible.builtin.blockinfile:
       dest: /etc/drill-site/drill-env.sh
       insertafter: EOF
       block: |     
         export HADOOP_HOME=/usr/local/hadoop
         export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
       backup: yes
       owner: suhailmsu21
