- hosts: amazon-*
  become_user: ubuntu
  tasks:
   - name: Editing core.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/core-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>fs.defaultFS</name>
         <value>hdfs://ec2-54-226-63-43.compute-1.amazonaws.com:9000</value>
         </property>
       backup: yes
       owner: ubuntu

   - name: Editing mapred.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/mapred-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>mapred.job.tracker</name>
         <value>ec2-54-226-63-43.compute-1.amazonaws.com:54311</value>
         </property>
         <property>
         <name>mapreduce.framework.name</name>
         <value>yarn</value>
         </property>
       backup: yes
       owner: ubuntu


   - name: Editing hdfs.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/hdfs-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>dfs.replication</name>
         <value>2</value>
         </property>
         <property>
         <name>dfs.namenode.name.dir</name>
         <value>file:///usr/local/hadoop/hdfs/data</value>
         </property>
         <property>
         <name>dfs.datanode.data.dir</name>
         <value>file:///usr/local/hadoop/hdfs/data</value>
         </property>
         <property>
         <name>dfs.permissions</name>
         <value>false</value>
         </property>
       backup: yes
       owner: ubuntu

   - name: Editing yarn-site.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/yarn-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>yarn.nodemanager.aux-services</name>
         <value>mapreduce_shuffle</value>
         </property>
         <property>
         <name>yarn.nodemanager.aux-services.mapreduce.shuffle.class</name>
         <value>org.apache.hadoop.mapred.ShuffleHandler</value>
         </property>
         <property>
         <name>yarn.resourcemanager.hostname</name>
         <value>ec2-54-226-63-43.compute-1.amazonaws.com</value>
         </property>
       backup: yes
       owner: ubuntu

   - name: Removing some lines in slaves start File
     ansible.builtin.lineinfile:
       path: /usr/local/hadoop/etc/hadoop/workers
       regexp: 'localhost'
       line: ''
       backrefs: yes
       owner: ubuntu



   - name: Modifying masters file
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/masters
       insertafter: EOF
       block: |
         ec2-54-226-63-43.compute-1.amazonaws.com
       backup: yes
       owner: ubuntu

   - name: Modifying slaves file
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/workers
       insertafter: EOF
       block: |
         ec2-3-95-14-23.compute-1.amazonaws.com
         ec2-34-230-31-93.compute-1.amazonaws.com
         ec2-54-196-181-216.compute-1.amazonaws.com
       backup: yes
       owner: ubuntu
   - name: Get apache hadoop
     get_url: 
       url: https://github.com/suhailshaik98/Configure-Apache-Hadoop/raw/main/hosts
       dest: /etc/hosts
       backup: yes
       owner: ubuntu
   - name: Rebooting Machines
     reboot:
