- hosts: google-*
  become_user: suhailmsu21
  tasks:
   - name: Editing mapred.xml File 
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/mapred-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>mapred.job.tracker</name>
         <value>10.128.0.3:54311</value>
         </property>
         <property>
         <name>mapreduce.framework.name</name>
         <value>yarn</value>
         </property>
         <property>
         <name>yarn.app.mapreduce.am.resource.mb</name>
         <value>2048</value>
         </property>
         <property>
         <name>mapreduce.map.memory.mb</name>
         <value>1024</value>
         </property>
         <property>
         <name>mapreduce.reduce.memory.mb</name>
         <value>1024</value>
         </property>
         <property>
         <name>yarn.app.mapreduce.am.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
         <property>
         <name>mapreduce.map.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
         <property>
         <name>mapreduce.reduce.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
       backup: yes
       owner: suhailmsu21

   - name: Editing yarn-site.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/yarn-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>yarn.nodemanager.aux-services</name>
         <value>mapreduce_shuffle</value>
         </property>
         <property>
         <name>yarn.nodemanager.aux-services.mapreduce.shuffle.class</name>
         <value>org.apache.hadoop.mapred.ShuffleHandler</value>
         </property>
         <property>
         <name>yarn.resourcemanager.hostname</name>
         <value>10.128.0.3</value>
         </property>
         <property>         
         <name>yarn.nodemanager.resource.memory-mb</name>
         <value>4000</value>
         </property>
         <property>
         <name>yarn.scheduler.maximum-allocation-mb</name>
         <value>4500</value>
         </property>
         <property>
         <name>yarn.scheduler.minimum-allocation-mb</name>
         <value>1024</value>
         </property>
         <property>
         <name>yarn.nodemanager.vmem-check-enabled</name>
         <value>false</value>
         </property>
         <property>
         <name>yarn.resourcemanager.ha.enabled</name>
         <value>true</value>
         </property>
         <property>
         <name>yarn.resourcemanager.zk-address</name>
         <value>google-1:2181,google-2:2181,google-3:2181</value>
         </property>
         <property>
         <name>yarn.resourcemanager.recovery.enabled</name>
         <value>true</value>
         </property>
         <property>
         <name>yarn.resourcemanager.ha.automatic-failover.enabled</name>
         <value>true</value>
         </property>
       backup: yes
       owner: suhailmsu21
