- hosts: google_*
  become: yes
  pre_tasks:
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       update_cache: yes

   - name: Installing java apt
     apt:
       name: openjdk-8-jdk-headless
       state: present   
   - name: Get apache hadoop
     get_url: 
       url: https://archive.apache.org/dist/hadoop/common/hadoop-3.1.1/hadoop-3.1.1.tar.gz
       dest: /home/suhailmsu21

   - name: Extract  hadoop
     ansible.builtin.unarchive:
       src: /home/suhailmsu21/hadoop-3.1.1.tar.gz
       dest: /home/suhailmsu21
       remote_src: True
       owner: suhailmsu21

   - name: removing existing hadoop file
     raw: rm -r -f /home/suhailmsu21/hadoop



   - name: changing directory from hadoop-3.1.1 to hadoop
     raw: mv hadoop-3.1.1 hadoop/

   - name: Change permission 
     ansible.builtin.file:
       path: /home/suhailmsu21/hadoop
       state: directory
       mode: '0755'
       owner: suhailmsu21
   - name: Make dir hdfstmp
     ansible.builtin.file:
       path: /home/suhailmsu21/hadoop/hdfs/data
       state: directory
       mode: '0700'
       owner: suhailmsu21


   - name: Modifying hosts file     
     ansible.builtin.copy:
       src: /etc/hosts
       dest: /etc/hosts

   - name: Editing Bash File
     
     ansible.builtin.blockinfile:
       dest: .bashrc
       insertafter: EOF
       block: |
         export HADOOP_HOME=/usr/local/hadoop
         export PATH=$PATH:$HADOOP_HOME/bin
         export PATH=$PATH:$HADOOP_HOME/sbin
         export HADOOP_MAPRED_HOME=${HADOOP_HOME}
         export HADOOP_COMMON_HOME=${HADOOP_HOME}
         export HADOOP_HDFS_HOME=${HADOOP_HOME}
         export YARN_HOME=${HADOOP_HOME}
         export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
         export SPARK_HOME=/usr/local/spark
         export PYSPARK_PYTHON=python3
         export PATH=$PATH:$SPARK_HOME/bin
         export LD_LIBRARY_PATH=$HADOOP_HOME/lib/native:$LD_LIBRARY_PATH
         export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH
         export ZOO_HOME=/usr/local/zookeeper
         export PATH=$ZOO_HOME/bin:$PATH
          function sparknotebook()
          {
          export PYSPARK_PYTHON=python3
          export SPARK_HOME=/usr/local/spark
          export PYSPARK_DRIVER_PYTHON=jupyter
          export PYSPARK_DRIVER_PYTHON_OPTS="notebook"
          $SPARK_HOME/bin/pyspark --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11
          }         
       backup: yes
   - name: Editing hadoop-env.sh
     
     ansible.builtin.lineinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/hadoop-env.sh
       insertafter: EOF
       line: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
       backup: yes
       owner: suhailmsu21



  post_tasks:
   - name: Editing core.xml File
     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/core-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>fs.defaultFS</name>
         <value>hdfs://amazon_1:9000</value>
         </property>
       backup: yes
       owner: suhailmsu21

   - name: Editing mapred.xml File
     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/mapred-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>mapred.job.tracker</name>
         <value>amazon_1:54311</value>
         </property>
         <property>
         <name>mapreduce.framework.name</name>
         <value>yarn</value>
         </property>
       backup: yes
       owner: suhailmsu21


   - name: Editing hdfs.xml File
     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/hdfs-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>dfs.replication</name>
         <value>3</value>
         </property>
         <property>
         <name>dfs.namenode.name.dir</name>
         <value>file:///usr/local/hadoop/hdfs/data</value>
         </property>
         <property>
         <name>dfs.datanode.data.dir</name>
         <value>file:///usr/local/hadoop/hdfs/data</value>
         </property>
       backup: yes
       owner: suhailmsu21

   - name: Editing yarn-site.xml File
     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/yarn-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>yarn.nodemanager.aux-services</name>
         <value>mapreduce_shuffle</value>
         </property>
         <property>
         <name>yarn.nodemanager.aux-services.mapreduce.shuffle.class</name>
         <value>org.apache.hadoop.mapred.ShuffleHandler</value>
         </property>
         <property>
         <name>yarn.resourcemanager.hostname</name>
         <value>amazon_1</value>
         </property>
       backup: yes
       owner: suhailmsu21

   - name: Make dir hadoop
     raw: sudo chown suhailmsu21:suhailmsu21 -R hadoop/hdfs/data
   - name: Make dir hadoop2
     raw: chmod 700 hadoop/hdfs/data

   - name: create file masters
     raw: touch /home/suhailmsu21/hadoop/etc/hadoop/masters


   - name: Modifying masters file
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/masters
       insertafter: EOF
       block: |
         amazon_1
       backup: yes
       owner: suhailmsu21

   - name: Modifying slaves file
     
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/hadoop/etc/hadoop/workers
       insertafter: EOF
       block: |
         amazon_2
         amazon_3
         amazon_4
       backup: yes
       owner: suhailmsu21
   - name: Transferring files to usr/local directory
     raw: mv hadoop /usr/local/hadoop


- hosts: google_1
  become: yes
  tasks:
   - name: Changing permissions of the key
     copy:
       src: /cst4570_suhail.pem
       dest: /home/suhailmsu21/
       mode: '400'
       owner: suhailmsu21
   - name: Installing jupyter notebook
     apt:
       name: jupyter-notebook
       state: present
   - name: Installing pip
     apt:
       name: python3-pip
       state: present
- hosts: google_1
  become_user: suhailmsu21
  tasks:
   - name: Installing pip
     pip:
       name: findspark
