- hosts: google-*
  become: yes
  tasks:

   - name: Get apache spark
     get_url: 
       url: https://dlcdn.apache.org/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz
       dest: /home/suhailmsu21

   - name: Extract spark
     ansible.builtin.unarchive:
       src: /home/suhailmsu21/spark-2.4.8-bin-hadoop2.7.tgz
       dest: /home/suhailmsu21
       remote_src: True
       owner: suhailmsu21

   - name: changing directory from spark-3.2.1 to spark
     raw: mv spark-2.4.8-bin-hadoop2.7 spark/
   - name: changing directory from spark conf template to spark conf
     raw: mv spark/conf/spark-defaults.conf.template spark/conf/spark-defaults.conf
   - name: removing old spark file
     raw: rm -r --f /usr/local/spark

 
   - name: Transferring files to usr/local directory
     raw: mv spark /usr/local/spark
 
   - name: update spark-defaults File
     ansible.builtin.blockinfile:
       dest: /usr/local/spark/conf/spark-defaults.conf
       insertafter: EOF
       block: |
         spark.master yarn
         spark.driver.memory 1g
         spark.yarn.am.memory 1g
         spark.executor.memory 14g
         spark.eventLog.enabled true
         spark.eventLog.dir hdfs://google-1:9000/spark-logs
         spark.history.provider org.apache.spark.deploy.history.FsHistoryProvider
         spark.history.fs.logDirectory hdfs://google-1:9000/spark-logs
         spark.history.fs.update.interval 10s
         spark.history.ui.port 18080
         spark.history.ui.enabled true
         spark.ui.enabled true
         spark.ui.killenabled true
         spark.ui.port 4040
       backup: yes
       owner: suhailmsu21     
