- hosts: amazon_1
  become: yes
  tasks:

   - name: Get apache spark
     get_url: 
       url: https://dlcdn.apache.org/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz
       dest: /home/ubuntu
   - name: Get apache sparkdl
     get_url: 
       url: https://github.com/databricks/spark-deep-learning/archive/154e7a68dffc9e94d83099216e8d1b98d5a0f566.zip
       dest: /home/ubuntu
   - name: Extract spark
     ansible.builtin.unarchive:
       src: /home/ubuntu/spark-3.0.3-bin-hadoop2.7.tgz
       dest: /home/ubuntu
       remote_src: True
       owner: ubuntu
   - name: Extract spark
     ansible.builtin.unarchive:
       src: /home/ubuntu/154e7a68dffc9e94d83099216e8d1b98d5a0f566.zip
       dest: /home/ubuntu
       remote_src: True
       owner: ubuntu
- name: Editing Bash File
     
     ansible.builtin.blockinfile:
       dest: .bashrc
       insertafter: EOF
       block: |
          export PYSPARK_PYTHON=python3
          export SPARK_HOME=/home/suhail/spark-2.4.8-bin-hadoop2.7
          export PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH

          function sparknotebook()
          {
          export PYSPARK_PYTHON=python3
          export SPARK_HOME=/usr/local/spark
          export PYSPARK_DRIVER_PYTHON=jupyter
          export PYSPARK_DRIVER_PYTHON_OPTS="notebook"
          $SPARK_HOME/bin/pyspark --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11
          }
       backup: yes

   - name: changing directory from spark-3.2.1 to spark
     raw: mv spark-3.0.3-bin-hadoop2.7 spark/
   - name: changing directory from sparkdl to spark
     raw: mv spark-deep-learning-154e7a68dffc9e94d83099216e8d1b98d5a0f566 deep-learning:1.5.0-spark2.4-s_2.1/
   - name: changing directory from spark conf template to spark conf
     raw: mv spark/conf/spark-defaults.conf.template spark/conf/spark-defaults.conf
   - name: removing old spark file
     raw: rm -r --f /usr/local/spark
   - name: Transferring files to usr/local directory
     raw: mv spark /usr/local/spark
   - name: Transferring files to usr/local directory
     raw: mv deep-learning:1.5.0-spark2.4-s_2.1 /usr/local/spark/deep-learning:1.5.0-spark2.4-s_2.1/
   - name: Installing jupyter notebook
     apt:
       name: jupyter-notebook
       state: present
   - name: Installing pip
     apt:
       name: python3-pip
       state: present

   - name: Installing findspark
     pip:
       name: findspark
   - name: Installing wrapt
     pip:
       name: tensorflow==1.4.1
       executable: pip3
   - name: Installing wrapt
     pip:
       name: tensorframes
       executable: pip3
   - name: Installing wrapt
     pip:
       name: wrapt
       executable: pip3
   - name: Installing wrapt
     pip:
       name: pillow==5.1.0
       executable: pip3
    - name: Installing wrapt
     pip:
       name: pandas==1.1.5
       executable: pip3
    - name: Installing wrapt
     pip:
       name: h5py
       executable: pip3
   - name: Installing wrapt
     pip:
       name: kafka
       executable: pip2
   - name: Installing wrapt
     pip:
       name: py4j
       executable: pip2
    - name: Installing wrapt
     pip:
       name: tensorflowonspark
       executable: pip2
    - name: Installing wrapt
     pip:
       name: jieba
       executable: pip2
  
