- hosts: amazon_*
  become: yes
  tasks:
 
   - name: update spark-defaults File
     ansible.builtin.blockinfile:
       dest: /usr/local/spark/conf/spark-defaults.conf
       insertafter: EOF
       block: |
         spark.master yarn
         spark.driver.memory 1g
         spark.yarn.am.memory 1g
         spark.executor.memory 15g
         spark.eventLog.enabled true
         spark.eventLog.dir hdfs://ec2-44-204-231-16.compute-1.amazonaws.com:9000/spark-logs
         spark.history.provider org.apache.spark.deploy.history.FsHistoryProvider
         spark.history.fs.logDirectory hdfs://ec2-44-202-222-30.compute-1.amazonaws.com/spark-logs
         spark.history.fs.update.interval 10s
         spark.history.ui.port 18080
         spark.history.ui.enabled true
         spark.ui.enabled true
         spark.ui.killenabled true
         spark.ui.port 4040
       backup: yes
       owner: ubuntu
