- hosts: amazon_*
  become_user: ubuntu
  tasks:
   - name: Editing mapred.xml File 
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/mapred-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>mapred.job.tracker</name>
         <value>ec2-44-203-222-156.compute-1.amazonaws.com:54311</value>
         </property>
         <property>
         <name>mapreduce.framework.name</name>
         <value>yarn</value>
         </property>
         <property>
         <name>yarn.app.mapreduce.am.resource.mb</name>
         <value>512</value>
         </property>
         <property>
         <name>mapreduce.map.memory.mb</name>
         <value>256</value>
         </property>
         <property>
         <name>mapreduce.reduce.memory.mb</name>
         <value>256</value>
         </property>
         <property>
         <name>yarn.app.mapreduce.am.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
         <property>
         <name>mapreduce.map.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
         <property>
         <name>mapreduce.reduce.env</name>
         <value>HADOOP_MAPRED_HOME=$HADOOP_MAPRED_HOME</value>
         </property>
       backup: yes
       owner: ubuntu

   - name: Editing yarn-site.xml File
     
     ansible.builtin.blockinfile:
       dest: /usr/local/hadoop/etc/hadoop/yarn-site.xml
       marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
       insertafter: "<configuration>"
       block: |
         <property>
         <name>yarn.nodemanager.aux-services</name>
         <value>mapreduce_shuffle</value>
         </property>
         <property>
         <name>yarn.nodemanager.aux-services.mapreduce.shuffle.class</name>
         <value>org.apache.hadoop.mapred.ShuffleHandler</value>
         </property>
         <property>
         <name>yarn.resourcemanager.hostname</name>
         <value>ec2-44-203-222-156.compute-1.amazonaws.com</value>
         </property>
         <property>         
         <name>yarn.nodemanager.resource.memory-mb</name>
         <value>1536</value>
         </property>
         <property>
         <name>yarn.scheduler.maximum-allocation-mb</name>
         <value>1536</value>
         </property>
         <property>
         <name>yarn.scheduler.minimum-allocation-mb</name>
         <value>128</value>
         </property>
         <property>
         <name>yarn.nodemanager.vmem-check-enabled</name>
         <value>false</value>
         </property>
       backup: yes
       owner: ubuntu

