- hosts: google_*
  become: yes
  tasks:
 #  - name: Run the equivalent of "apt-get update" as a separate step
 #    apt:
 #      update_cache: yes
   - name: apt install zookeeper
     apt:
       name: zookeeperd
       state: present
#      update_cache: yes
   - name: Editing zoo.cfg File
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/zoo.cfg
       block: |
         tickTime = 2000
         syncLimit = 5
         dataDir = /usr/share/zookeeper/data
         clientPort= 2181
         server.1 = 10.128.0.3 : 2888 : 3888
         server.2 = 10.128.0.3 : 2888 : 3888
       backup: yes
       owner: suhailmsu21 
   - name: Get apache hadoop
     get_url: 
       url: https://dlcdn.apache.org/drill/drill-1.20.1/apache-drill-1.20.1.tar.gz
       dest: /home/suhailmsu21

   - name: Extract  drill
     ansible.builtin.unarchive:
       src: /home/suhailmsu21/apache-drill-1.20.1.tar.gz
       dest: /home/suhailmsu21
       remote_src: True
       owner: suhailmsu21
   - name: removing existing drill
     raw: rm -r -f /etc/zookeeper/data
   - name: Make dir data
     raw: sudo mkdir /etc/zookeeper/data/
   - name: removing existing drill
     raw: rm -r -f /usr/local/apache-drill
   - name: make myid file
     raw: sudo touch /etc/zookeeper/data/myid
   - name: remove drill-on-yarn file
     raw: sudo rm -r -f /etc/drill-site     
   - name: remove conf of drill-on-yarn file
     raw: sudo rm -r -f /usr/local/apache-drill/conf/drill-on-yarn.conf

   - name: changing directory from hadoop-3.1.1 to hadoop
     raw: mv apache-drill-1.20.1 /usr/local/apache-drill/
   - name: make drill-on-yarn file
     raw: sudo mkdir /etc/drill-site
   - name: make drill-on-yarn file
     raw: sudo touch /usr/local/apache-drill/conf/drill-on-yarn.conf
   - name: make copy files from DRILL HOME
     raw: sudo cp /usr/local/apache-drill/conf/drilloverrideexample.conf $DRILL_SITE/drill-override.conf
   - name: make copy files from DRILL HOME
     raw: sudo cp /usr/local/apache-drill/conf/drill-on-yarnexample.conf $DRILL_SITE/drill-on-yarn.conf
   - name: make copy files from DRILL HOME
     raw: sudo cp /usr/local/apache-drill/conf/drillenv.sh $DRILL_SITE     
   - name: Editing drill-override.conf
     
     ansible.builtin.blockinfile:
       dest: /etc/drill-site/drill-override.conf
       insertafter: EOF
       block: |     
          drill.exec:{
            cluster-id: "cluster1",
            zk.connect: "10.128.0.3:2181,10.128.0.4:2181"
          }
       backup: yes
       owner: suhailmsu21 
   - name: Editing Bash File
     ansible.builtin.blockinfile:
       dest: /etc/drill-on-yarn.conf
       insertafter: EOF
       block: |     
         drillbit: {
           heap: "4G"
           max-direct-memory: "8G"
           memory-mb: 6144
           vcores: 4
         }
       backup: yes
       owner: suhailmsu21 
- hosts: google_1
  become: yes
  tasks:
   - name: Editing MYID File
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         1
       backup: yes
       owner: suhailmsu21     
- hosts: google_2
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         2
       backup: yes
       owner: suhailmsu21
    
#https://dlcdn.apache.org/drill/drill-1.20.1/apache-drill-1.20.1.tar.gz

