- hosts: amazon_*
  become: yes
  tasks:
 #  - name: Run the equivalent of "apt-get update" as a separate step
 #    apt:
 #      update_cache: yes
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
       name: zookeeperd
       state: present
#      update_cache: yes
   - name: Editing zoo.cfg File
     ansible.builtin.blockinfile:
       dest: /usr/share/zookeeper/conf/zoo.cfg
       block: |
         tickTime = 2000
         syncLimit = 5
         dataDir = /usr/local/zookeeper/data
         clientPort= 2181
         server.1 = ec2-54-87-14-85.compute-1.amazonaws.com : 2888 : 3888
         server.2 = ec2-18-215-157-9.compute-1.amazonaws.com : 2888 : 3888
         server.3 = ec2-54-86-137-207.compute-1.amazonaws.com : 2888 : 3888
       backup: yes
       owner: ubuntu 
- hosts: amazon_1
  become: yes
  tasks:
   - name: Editing MYID File
     ansible.builtin.blockinfile:
       dest: /usr/share/zookeeper/data/myid
       block: |
         1
       backup: yes
       owner: ubuntu     
- hosts: amazon_2
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /usr/share/zookeeper/data/myid
       block: |
         2
       backup: yes
       owner: ubuntu
- hosts: amazon_3
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /usr/local/zookeeper/data/myid
       block: |
         3
       backup: yes
       owner: ubuntu      

