- hosts: google-*
  become: yes
  tasks:
   - name: Changing name of the file zookeeper
     raw: rm -r -f /etc/zookeeper
   - name: Get apache zookeeper
     unarchive: 
       src: https://archive.apache.org/dist/zookeeper/zookeeper-3.5.8/apache-zookeeper-3.5.8-bin.tar.gz
       dest: /home/suhailmsu21
       backup: yes
       remote_src: yes
       owner: suhailmsu21        
   - name: Installing zookeeperd apt
     apt:
       name: zookeeperd
       state: present      
   - name: Changing name of the file zookeeper
     raw: rm -r -f zookeeper  
   - name: Changing name of the file zookeeper
     raw: mv apache-zookeeper-3.5.8-bin zookeeper
   - name: Changing name of the file zookeeper
     raw: mkdir /etc/zookeeper/data
   - name: Creating zoo.cfg file
     raw: touch /home/suhailmsu21/zookeeper/conf/zoo.cfg
   - name: Creating myid file
     raw: touch /etc/zookeeper/data/myid     
   - name: Editing zoo.cfg File
     ansible.builtin.blockinfile:
       dest: /home/suhailmsu21/zookeeper/conf/zoo.cfg
       block: |
         tickTime=2000
         dataDir=/etc/zookeeper/data
         clientPort=2181
         initLimit=5
         syncLimit=2      
         server.1=google-1:2888:3888
         server.2=google-2:2888:3888
         server.3=google-3:2888:3888
         server.4=google-4:2888:3888
       backup: yes
       owner: suhailmsu21 
   - name: Creating myid file
     raw: rm -r -f  /usr/share/zookeeper
   - name: Creating myid file
     raw: mv zookeeper /usr/share/zookeeper
 
   - name: Remove zoo.cfg from etc
     raw: rm -r -f  /etc/zookeeper/conf/zoo.cfg
   - name: Remove zoo.cfg from etc
     raw: rm -r -f  /etc/zookeeper/conf/myid     
   - name: Creating zoo.cfg file
     raw: touch /etc/zookeeper/conf/zoo.cfg
   - name: Creating zoo.cfg file
     raw: touch /etc/zookeeper/conf/myid     
   - name: Editing zoo.cfg File
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/zoo.cfg
       block: |
         tickTime=2000
         dataDir=/etc/zookeeper/data
         clientPort=2181
         initLimit=5
         syncLimit=2      
         server.1=google-1:2888:3888
         server.2=google-2:2888:3888
         server.3=google-3:2888:3888
         server.4=google-4:2888:3888
       backup: yes
       owner: suhailmsu21

   
- hosts: google-3
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         3
       backup: yes
       owner: ubuntu
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/myid
       block: |
         3
       backup: yes
       owner: suhailmsu21
- hosts: google-2
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         2
       backup: yes
       owner: ubuntu
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/myid
       block: |
         2
       backup: yes
       owner: suhailmsu21
- hosts: google-1
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         1
       backup: yes
       owner: suhailmsu21
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/myid
       block: |
         1
       backup: yes
       owner: suhailmsu21
- hosts: google-4
  become: yes
  tasks:
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/data/myid
       block: |
         4
       backup: yes
       owner: suhailmsu21
   - name: Editing MYID file
     ansible.builtin.blockinfile:
       dest: /etc/zookeeper/conf/myid
       block: |
         4
       backup: yes
       owner: suhailmsu21
#- hosts: google-1
 # become: yes
  #tasks:
  # - name: Editing MYID file
   #  ansible.builtin.blockinfile:
   #    dest: /etc/zookeeper/data/myid
   #    block: |
   #      4
   #    backup: yes
   #    owner: suhailmsu21    
#https://dlcdn.apache.org/drill/drill-1.20.1/apache-drill-1.20.1.tar.gz

